version: '3.7'
services:
        app:
                container_name: api
                build:
                        context: ./
                        dockerfile: docker/app/Dockerfile 
                ports:
                        - "5000:5000"
                volumes:
                        - .:/app
